//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MediaPlayer.rc
//
#define IDW_PLR                         0
#define IDW_RAD                         1
#define IDW_LST                         2
#define IDW_SRT                         3
#define IDW_MDB                         4
#define IDW_VID                         5
#define IDW_MXR                         6
#define IDW_max                         7
#define IDI_PLR                         101
#define IDI_LST                         102
#define IDI_SRT                         103
#define IDI_LIB                         104
#define IDI_VIS                         105
#define IDI_RAD                         105
#define IDI_VID                         106
#define IDI_MXR                         107
#define IDI_CFG                         108
#define IDI_SPK_ON                      109
#define IDI_SPK_OFF                     110
#define IDI_OSK                         111
#define IDI_PLAY                        201
#define IDI_NEXT                        202
#define IDI_PREV                        203
#define IDI_STOP                        204
#define IDI_PAUSE                       205
#define IDI_PLAYNOW                     209
#define IDI_PLAYNEXT                    210
#define IDI_PLAYQUEUE                   211
#define IDI_REMOVE                      212
#define IDI_ARTIST                      213
#define IDI_EXIT                        214
#define IDI_DEL                         215
#define IDI_LISTALBUM                   218
#define IDI_LISTTRACK                   219
#define IDI_STOPPED                     220
#define IDI_PLAYING                     221
#define IDI_PAUSED                      222
#define IDI_RDS                         224
#define IDI_ICON1                       225
#define IDI_RDSSM                       225
#define IDI_THUMBSUP                    226
#define IDI_THUMBSDOWN                  227
#define IDI_EDIT                        228
#define IDI_INFO                        229
#define IDI_ADDFOLDER                   231
#define IDI_DELFOLDER                   232
#define IDI_UPDATE                      233
#define IDI_FILE                        234
#define IDI_REPEAT                      235
#define IDI_LEFT                        236
#define IDI_RIGHT                       237
#define IDI_DELALL                      238
#define IDI_SCANUP                      239
#define IDI_SCANDOWN                    240
#define IDI_TUNEUP                      241
#define IDI_TUNEDOWN                    242
#define IDI_UP                          243
#define IDI_DOWN                        244
#define IDI_RSSI0                       245
#define IDI_RSSI1                       246
#define IDI_RSSI2                       247
#define IDI_RSSI3                       248
#define IDI_RSSI4                       249
#define IDI_RSSI5                       250
#define IDI_PLAYALL                     251
#define IDI_RECORD                      252
#define IDI_TAON						253
#define IDI_ENABLE						254
#define IDI_DISABLE						255
#define IDC_COMMAND                     1000
#define IDC_PLR                         1001
#define IDC_RAD                         1002
#define IDC_LST                         1003
#define IDC_SRT                         1004
#define IDC_MDB                         1005
#define IDC_VID                         1006
#define IDC_MXR                         1007
#define IDC_SPK                         1008
#define IDC_MUTE                        1009
#define IDC_PLAY                        1101
#define IDC_NEXT                        1102
#define IDC_PREV                        1103
#define IDC_STOP                        1104
#define IDC_PAUSE                       1105
#define IDC_SHUFFLE                     1106
#define IDC_XFADE                       1107
#define IDC_REPEAT                      1108
#define IDC_PLAYNOW                     1109
#define IDC_PLAYNEXT                    1110
#define IDC_REMOVE                      1111
#define IDC_SEEK                        1112
#define IDC_TICKER                      1113
#define IDC_SUBTICKER                   1114
#define IDC_COMINGNEXT                  1115
#define IDC_STATUS                      1116
#define IDC_HIDE                        1117
#define IDC_EDIT                        1118
#define IDC_REMOVEALL                   1119
#define IDC_POINTINC                    1120
#define IDC_POINTDEC                    1121
#define IDC_EDITCURR                    1122
#define IDC_DELETE                      1123
#define IDC_INFO                        1124
#define IDC_RATING                      1125
#define IDC_SPECTRUM                    1126
#define IDC_RDSTA                       1127
#define IDC_RDSTICKER                   1114
#define IDC_OSK                         1301
#define IDC_SORTARTIST                  1401
#define IDC_SORTALBUM                   1402
#define IDC_SORTTITLE                   1403
#define IDC_SORTLIST                    1404
#define IDC_SORTRESULT                  1405
#define IDC_SORTPLAYNOW                 1406
#define IDC_SORTPLAYNEXT                1407
#define IDC_SORTPLAYQUEUE               1408
#define IDC_SORTSHOW                    1409
#define IDC_SORTSELALL                  1410
#define IDC_SCROLLLIST                  1411
#define IDC_SCROLLRESULT                1412
#define IDC_SORTPLAYALL                 1413
#define IDC_MDBOSK                      1501
#define IDC_MDBARTIST                   1502
#define IDC_MDBALBUM                    1503
#define IDC_MDBTITLE                    1504
#define IDC_MDBLIST                     1505
#define IDC_SCANUP                      1600
#define IDC_SCANDOWN                    1601
#define IDC_TUNEUP                      1602
#define IDC_TUNEDOWN                    1603
#define IDC_UP                          1604
#define IDC_DOWN                        1605
#define IDC_RECORD                      1606
#define IDC_STATIONS                    1607
#define IDC_DX							1608
#define IDC_MONO						1609
#define IDC_CFGABORT                    1802
#define IDC_CFGEXIT                     1803
#define IDC_CFGDELETEDB                 1804
#define IDC_CFGDELETECFG                1805
#define IDC_DIRLIST                     1806
#define IDC_ADDFOLDER                   1807
#define IDC_DELFOLDER                   1809
#define IDC_UPDATE                      1810
#define IDC_GARBAGECOLLECTION           1811
#define IDC_POPUP                       1812
#define IDC_WIDESCREEN                  1813
#define IDC_DIR                         2001
#define IDC_SEL                         2002
#define IDC_OK                          2003
#define IDC_CANCEL                      2004
#define IDC_GO                          2005
#define IDC_CURDIR                      2006
#define IDC_CARGOLOGO					2007
#define IDC_SETTINGS					2008
#define IDC_ENABLE						2009
#define IDC_DISABLE						2010
#define IDC_SETTDESCR					2011

#define IDB_THUMBSUP                    3001
#define IDB_THUMBSDOWN                  3002
#define IDB_CARGO                  		3003
#define IDB_DESTUP                      9001
#define IDB_DESTDOWN                    9002
#define IDB_DESTOFF                     9003

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        228
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           201
#endif
#endif
